remote_theme: ankitsultana/researcher

# Site settings
title: "Dino Grgić"
description: "Dino Grgić's personal portfolio website"
author: "Dino Grgić"
email: dino.grgic1@gmail.com
url: "https://dino-grgic.github.io"
baseurl: ""

future: true

github_username: dino-grgic
linkedin_username: dinogrgic

nav:
  - name: "About"
    link: "/"
  - name: "Resume"
    link: "/cv/cv_en.pdf"
  - name: "Contact"
    link: "mailto:dino.grgic1@gmail.com"

plugins:
  - jekyll-remote-theme

markdown: kramdown
highlighter: rouge
sass:
  style: compressed

collections:
  projects:
    output: true
    permalink: /:collection/:name/
  presentations:
    output: true
    permalink: /presentations/:name/

defaults:
  - scope:
      path: ""
      type: "presentations"
    values:
      layout: "presentations"